version: '3.6'

volumes:
    hello:
      driver: local

services:
  webservice:
    build: ./webservice
    depends_on:
      - db
    environment:
      POSTGRES_USER: test
      POSTGRES_HOST: db
      POSTGRES_PASSWORD: test
      POSTGRES_DB: test
      POSTGRES_PORT: 5432
    networks:
      - default
    ports:
      - 5000:5000
    # restart: always

  db:
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
      POSTGRES_DB: test
    image: postgres:latest
    networks:
      - default
    ports:
      - 5432:5432
    volumes:
      - hello:/var/lib/postgresql/data
    # restart: always